language: node_js
node_js: 16
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: blckchnd/rudex-ui
        - ORGANIZATION_REPO: blckchnd/rudex.org
        - WALLET_REPO: blckchnd/market.rudex.org
        - CXX=g++-4.8
        - secure: QEIqqSio+7rPwcPI9jXpykKRVNEt12dzUKo50CVIGwJpF9BkGtTADc51dseFft1ZYPI+zsGd0E9PmQlCGjDj9Dz3fY8J8D4YWtN8T9HJtVH86nCJNWfAI7kNmuF2eam4UqRIg+1Wnm2BWdvzMt1Fkt5wvaQ+xNF7eKvTYACcXlJgVkK+BEyEL5xPlecxEJ536F8I1UziTXNwY5bciwwxLDuqrhnkQkBAs5SGtiyjWJ1WHwcCx8kDCRh2LP/OlegLmfx3Xag/4tGt+2eyVnvNoFYT+/P7CRN9GO9o0ZgBwYVy39K4qdrR+XWP7Dt6hkB5CqDpOno/kdGDwcZRw8KHIq5BI7qQvAWN7Q4LigRsjAAu1OAwY9xKH/3CeSWILr/pT/m6BpuiuFvunjxIARmQXk2ThEA6oPKj7YZgKOdag18o7/Kn+2eLOeR14UVHqt7aBH8wVAFULWRFzyWF2S6+l7+UGWsCyvG+swSymh3OlQXNEGTKZ42n5YgW9q+EymVUDHZmPsUJunMrbBWaai6VEUnnMJu3KbXLJ/F0AaTJe7R0J9U1wiON3T6a9NYE6eKSr0xIE2DGsFIm5vrpXop5JqavD2uFm9Dpysa/AU41ma8dauavV65x6dN7ZLeymidUdjnGjFPZzLqLuUC6BwYXxC2YTF8jADyKYcEZB/eQIHo=
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    # - npm ci
    - yarn
script:
    - "./build.sh"
after_success: "./deploy.sh"
deploy:
    - provider: releases
      tag_name: "$TRAVIS_TAG"
      name: "$TRAVIS_TAG"
      body: "Automated release from Travis CI with added files from AppVeyor build"
      api_key:
          secure: WJXIYvyVn5VigQ6gsa8n+PjtDS/E+F9pQouzvJ8NAhUWVgDtEzLGm0jDRg9gsh/zmeB14eiyCrkNYH45FYiTMWDz+8ydzJXeBoWkpwduFWPb1sifRrEuPVUIJ2mDK5UBW4eobQHNda9taUxTBL/VdgZC9KLFuzhwzcFkdkLcBuLZYrmvgziEmJNkQ4/eHc6+n/Hug+dTDIenKcSbw8RH2AZNnGqQOCqEpl8LNMUhl6RczGXC8uu49EMPOON8Km+nlh4frkImbXuXMyudPl3iwTMiZE6xPex5IHS3vbaEbKfJTprNLFnyZyOZnhUCDNatNsRTlrQLMoQgEMYStb9huI/xVdJ6hKZgdVNjiu2ZCYUyxmy2WxBuGc0GBXrojJX4x4U7/+cXohk3DNBMLDcRPQAqWAtre/arIAJLJDi+hVFOmsi03KoWt5F7wduPQe8liaQtLDTa490tdIpJqyUgEKFSEciazkhjd9ggiob2lj+kCfWNe4kPzUogJ+MoenxctIk4aQE/FumnoyjkgOd3bEGMik3B41X6UpRDWqOtkvDRfPw9Pqd9EzjfRiaS7VsjO/ehYflOAdBvpy/PmvYIjdFl/Ij2h3tny74ze4ywVk2xLfN+CQtESHvwVAC1nvcyMvmUj5Wk7eBBnwJeYYGDUhPrB74HMzAFhBgPhq8MfTs=
      file_glob: true
      file:
          - build/binaries/RuDEX*
          - build/release-checksums-*
      skip_cleanup: true
      draft: true
      on:
          repo: blckchnd/rudex-ui
          tags: true
